[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]] # カーソル位置のコンテキストのfiletypeを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # コメント
repo = 'tomtom/tcomment_vim'


[[plugins]] # インデントに色を付けて見やすくする
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # シングル・ダブルクウォートの入れ替えなど
repo = 'tpope/vim-surround'

[[plugins]] # ステータスラインの色付け
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \   'colorscheme': 'molokai'
    \}
'''

[[plugins]] # Agコマンドで検索を高速にする
repo = 'rking/ag.vim'

[[plugins]] # テキスト揃えを簡単に実現する
repo = 'junegunn/vim-easy-align'

[[plugins]] # 任意の２か所のdiffをマークする
repo = 'AndrewRadev/linediff.vim'

[[plugins]] # コードチェック
repo = 'scrooloose/syntastic'

[[plugins]] # .eslintrcをプロジェクト毎変更可能に
repo = 'pmsorhaindo/syntastic-local-eslint.vim'

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'

# スニペット

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # php
repo = 'violetyk/neocomplete-php.vim'

# Git関連

[[plugins]] # vim用gitラッパープラグイン
repo ='tpope/vim-fugitive'

[[plugins]] # git の変更箇所をマーク
repo = 'airblade/vim-gitgutter'

# カラースキーム

[[plugins]]
repo = 'sjl/badwolf'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme badwolf
# '''

[[plugins]]
repo = 'tomasr/molokai'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme molokai
# '''

[[plugins]]
repo = 'w0ng/vim-hybrid'
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme hybrid
# '''

