[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1 # インサートモードに入ったら起動

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1

###########################################
# シンタックス
###########################################

[[plugins]] # TOMLシンタックス
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]] # ES6
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = 'ejs'

[[plugins]]
repo = 'vim-scripts/smarty-syntax'

[[plugins]]
repo = 'beyondwords/vim-twig'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

